[package]
name = "adhar"
version = "0.1.0"
edition = "2021"

[dependencies]

num-bigint = "0.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
flate2 = "1.0.35"
base64 = "0.22.1"
hex = "0.4.3"